name: ci

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build app
        uses: docker/build-push-action@v5
        with:
          context: app
          load: true
      - name: Build nginx
        uses: docker/build-push-action@v5
        with:
          context: nginx
          load: true
      - name: Build cron
        uses: docker/build-push-action@v5
        with:
          context: cron
          load: true
      - name: Build db
        uses: docker/build-push-action@v5
        with:
          context: db
          load: true
